### ISSUE TITLE
Consejo: usar ng-model para hacer el binding en los input

### ISSUE THREAD

**Issue by ivangsa** [Curso-Fullstack-MEAN-Octubre2017/HugoParapar#15]
https://github.com/Curso-Fullstack-MEAN-Octubre2017/HugoParapar/blob/474bed5223d78640d334c1759f52f1e0acccc961/public/app/customer-detail-module/customer-detail-module.html#L7

**Comment by hugoparapar** [comment]
Cambio realizado.
` <input type="text" ng-model="firstName" name="firstName"><br>`
